// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ConfigureUIClient is the client API for ConfigureUI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ConfigureUIClient interface {
	// ListEngineSpecs returns a list of Configuration Engine(s) that can be started through the UI.
	ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (ConfigureUI_ListEngineSpecsClient, error)
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error)
}

type configureUIClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigureUIClient(cc grpc.ClientConnInterface) ConfigureUIClient {
	return &configureUIClient{cc}
}

func (c *configureUIClient) ListEngineSpecs(ctx context.Context, in *ListEngineSpecsRequest, opts ...grpc.CallOption) (ConfigureUI_ListEngineSpecsClient, error) {
	stream, err := c.cc.NewStream(ctx, &ConfigureUI_ServiceDesc.Streams[0], "/v1.ConfigureUI/ListEngineSpecs", opts...)
	if err != nil {
		return nil, err
	}
	x := &configureUIListEngineSpecsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ConfigureUI_ListEngineSpecsClient interface {
	Recv() (*ListEngineSpecsResponse, error)
	grpc.ClientStream
}

type configureUIListEngineSpecsClient struct {
	grpc.ClientStream
}

func (x *configureUIListEngineSpecsClient) Recv() (*ListEngineSpecsResponse, error) {
	m := new(ListEngineSpecsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *configureUIClient) IsReadOnly(ctx context.Context, in *IsReadOnlyRequest, opts ...grpc.CallOption) (*IsReadOnlyResponse, error) {
	out := new(IsReadOnlyResponse)
	err := c.cc.Invoke(ctx, "/v1.ConfigureUI/IsReadOnly", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigureUIServer is the server API for ConfigureUI service.
// All implementations must embed UnimplementedConfigureUIServer
// for forward compatibility
type ConfigureUIServer interface {
	// ListEngineSpecs returns a list of Configuration Engine(s) that can be started through the UI.
	ListEngineSpecs(*ListEngineSpecsRequest, ConfigureUI_ListEngineSpecsServer) error
	// IsReadOnly returns true if the UI is readonly.
	IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error)
	mustEmbedUnimplementedConfigureUIServer()
}

// UnimplementedConfigureUIServer must be embedded to have forward compatible implementations.
type UnimplementedConfigureUIServer struct {
}

func (UnimplementedConfigureUIServer) ListEngineSpecs(*ListEngineSpecsRequest, ConfigureUI_ListEngineSpecsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListEngineSpecs not implemented")
}
func (UnimplementedConfigureUIServer) IsReadOnly(context.Context, *IsReadOnlyRequest) (*IsReadOnlyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsReadOnly not implemented")
}
func (UnimplementedConfigureUIServer) mustEmbedUnimplementedConfigureUIServer() {}

// UnsafeConfigureUIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigureUIServer will
// result in compilation errors.
type UnsafeConfigureUIServer interface {
	mustEmbedUnimplementedConfigureUIServer()
}

func RegisterConfigureUIServer(s grpc.ServiceRegistrar, srv ConfigureUIServer) {
	s.RegisterService(&ConfigureUI_ServiceDesc, srv)
}

func _ConfigureUI_ListEngineSpecs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListEngineSpecsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ConfigureUIServer).ListEngineSpecs(m, &configureUIListEngineSpecsServer{stream})
}

type ConfigureUI_ListEngineSpecsServer interface {
	Send(*ListEngineSpecsResponse) error
	grpc.ServerStream
}

type configureUIListEngineSpecsServer struct {
	grpc.ServerStream
}

func (x *configureUIListEngineSpecsServer) Send(m *ListEngineSpecsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _ConfigureUI_IsReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IsReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigureUIServer).IsReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/v1.ConfigureUI/IsReadOnly",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigureUIServer).IsReadOnly(ctx, req.(*IsReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConfigureUI_ServiceDesc is the grpc.ServiceDesc for ConfigureUI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfigureUI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "v1.ConfigureUI",
	HandlerType: (*ConfigureUIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsReadOnly",
			Handler:    _ConfigureUI_IsReadOnly_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListEngineSpecs",
			Handler:       _ConfigureUI_ListEngineSpecs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "configure-ui.proto",
}
